notifications:
  email: false

sudo: false

language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6

matrix:
  fast_finish: true

before_install:
  - travis_retry pip install --upgrade pip setuptools

install:
  - pip install -e .[tests]

script:
  - ./run-tests.sh

deploy:
  provider: pypi
  user: jacquerie
  password:
    secure: "JtXmoKA3u2mz3jBbhj1b8TMf9zlxgwSxJEN3cT68g/Ce5a+DYM2Ev6/AMtXNwh9SShgIDqzMifVC0Q7G4aK/8eNbW0M/57m6rFzI+idpcvowghVDToIHoN/GaHtOJ7L+euhvEkrTiwwhtoQ8yF52IVdTmoVAO39qyjRf3YEhhIEj8031IQMMVCjOQKf9c3/7K8fH8/q4VQCjsxCtMp+ySTM4f3Wmhv4bVuHRhNGQSbQWDjNrinAJgo8IYfFITIeJuO0SRG73Km52weZM/o+HAWESKvJAvS+Z5HWN+KS3xBqXEASK2KfiJZcPb1FTzyiWpFyr7YvZqclosimZubkB4F9TctKa0AvaQ+QB/KNqkWpQDMn+/elPv+mmZm9bkV+J4Hlf9OcRcFDsqiybkwbyShezUH5DdxJbGy1FaOax9H54e+d2YlpNwAPyHVybUUlPaXs/ypzVqlm85bEWD528117Yj4/tNtb00KMLHxvUGhWZRZa8Ka7A013+yjkWSW4MReTSsvCv1G40Yxo7rjr7IFAca23nP9jPuuO5xmJpgsRvPdjUdiX5FhLMGMJcDFEItjWLJVfE4tKFNjJeNepU3jAUgxLBZ/sbzrB3j8QpXTNXoOLbpPfHJ82AQWpbwhVRFcEVprlLTN9Swmyftz82HRvUfNHTSg0lfn2yfa0jF4g="
  on:
    branch: master
    python: 2.7
  distribution: sdist
